AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for sns-blog

Resources:

  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: 'example@gmail.com' #Add the user email
          Protocol: "email"
      TopicName: "SampleTopic"

  MyRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyRestAPI

  MyResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref MyRestApi
      ParentId: !GetAtt 
        - MyRestApi
        - RootResourceId
      PathPart: sendMail

  MyRequestValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties: 
      Name: MyRequestValidator
      RestApiId:  !Ref MyRestApi
      ValidateRequestBody: false
      ValidateRequestParameters: true

  MyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !Ref MyResource
      RestApiId: !Ref MyRestApi
      AuthorizationType: NONE
      RequestValidatorId: !Ref MyRequestValidator
      RequestParameters:
        method.request.querystring.message: true
        method.request.querystring.topic: true
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        PassthroughBehavior: never
        Credentials: !Sub '${MyRole.Arn}' 
        Uri: !Sub  'arn:aws:apigateway:${AWS::Region}:sns:action/Publish'
        RequestParameters:
          integration.request.querystring.Message : method.request.querystring.message
          integration.request.querystring.TopicArn : method.request.querystring.topic
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
  
  MyDeployment:
    DependsOn: MyMethod
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref MyRestApi
      Description: My testdeployment
      StageName: Test

  MyRole: 
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'sns:Publish'
                Resource: !Ref MySNSTopic
      


